### ISSUE TITLE
probably not an issue

### ISSUE THREAD

**Issue by jalbertbowden** [benbalter/dc-maps#9]
this isn't an issue, so sorry for posting as one...
i'd like to add all of these to the code for dc open data portal, and am wondering about the sources of the data. i'll point them all to here, but do you have any other citations/sources?
were these ripped from some place(s) in particular, or just hand gathered by you?
great job, this repo is nice.

**Comment by benbalter** [comment]
https://github.com/benbalter/dc-maps#source

**Comment by jalbertbowden** [comment]
not sure how i missed that. my bad, apologies
